# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dummy <- function(x, y) {
    .Call(`_logisticGP_dummy`, x, y)
}

colsums_cpp <- function(A) {
    .Call(`_logisticGP_colsums_cpp`, A)
}

#' hBasis function.
#' @param x A numeric vector.
#' @param knot A numeric vector.
#' @return A matrix.
#' @export
hBasis <- function(x, knot) {
    .Call(`_logisticGP_hBasis`, x, knot)
}

PhiBasis <- function(x, knot) {
    .Call(`_logisticGP_PhiBasis`, x, knot)
}

logcond_likelihood_beta <- function(xi, beta, tau, h_loc, X_new, h_y, test_knots) {
    .Call(`_logisticGP_logcond_likelihood_beta`, xi, beta, tau, h_loc, X_new, h_y, test_knots)
}

logcond_likelihood <- function(xi, beta, tau, h_loc, X_new, h_y, test_knots, H_Z) {
    .Call(`_logisticGP_logcond_likelihood`, xi, beta, tau, h_loc, X_new, h_y, test_knots, H_Z)
}

